---
dist: xenial
language: python
matrix:
  include:
    - python: "3.5"
      env: TOXENV=py3
    - python: "3.6"
      env: TOXENV=py3
    - python: "3.7"
      env: TOXENV=py3
    - python: "pypy3.5"
      env: TOXENV=pypy3

install:
  - pip install tox
script:
  - tox
